insert into `genre`
VALUES (1, 'ACTION'),
       (2, 'ADVENTURE'),
       (3, 'BIOGRAPHICAL'),
       (4, 'COMEDY'),
       (5, 'CRIME'),
       (6, 'DISASTER'),
       (7, 'DOCUMENTARY'),
       (8, 'DRAMA'),
       (9, 'EROTIC'),
       (10, 'FANTASY'),
       (11, 'HISTORICAL'),
       (12, 'HORROR'),
       (13, 'ROMANTIC'),
       (14, 'SCIENCE_FICTION'),
       (15, 'THRILLER'),
       (16, 'WESTERN');